-- Flyway Migration: Add missing Razorpay columns to user_subscriptions table

-- Since PhysicalNamingStrategyStandardImpl is used and PostgreSQL folds unquoted identifiers to lowercase, 
-- we add the columns in lowercase to perfectly match the SQL queries generated by Hibernate.

ALTER TABLE user_subscriptions 
ADD COLUMN IF NOT EXISTS razorpaycustomerid VARCHAR(255);

ALTER TABLE user_subscriptions 
ADD COLUMN IF NOT EXISTS razorpaysubscriptionid VARCHAR(255);
